### ISSUE TITLE
Ensure "extras" command is appended

### ISSUE THREAD

**Issue by surminus** [surminus/terragov#1]
The "extras" command needs to be appended to the back of the command

**Comment by surminus** [comment]
This is tricky with commander because when we try to add additional commands it complains:

```
➜  ~/surminus/terragov git:(master) ✗ DEBUG=true bin/terragov plan -d ~/govuk/govuk-aws-data/data -e integration -p app-backend -s blue -r ~/govuk/govuk-aws --verbose --trace --extra "-target resource.foo"
/Users/laura/.bundle/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:164:in `parse_options_and_call_procs': invalid option: -target resource.foo (OptionParser::InvalidOption)
	from /Users/laura/.bundle/ruby/2.4.0/gems/commander-4.4.3/lib/commander/command.rb:153:in `run'
	from /Users/laura/.bundle/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:446:in `run_active_command'
	from /Users/laura/.bundle/ruby/2.4.0/gems/commander-4.4.3/lib/commander/runner.rb:68:in `run!'
	from /Users/laura/.bundle/ruby/2.4.0/gems/commander-4.4.3/lib/commander/delegates.rb:15:in `run!'
	from /Users/laura/surminus/terragov/lib/terragov/cli.rb:163:in `run'
	from bin/terragov:4:in `<main>'
```

**Comment by surminus** [comment]
Added a note: https://github.com/surminus/terragov/commit/f9b352c4db6967e64411b04780879e6048cbeed6

**Comment by surminus** [comment]
Extra arguments can now be called by using a double escape, ie

`terraform plan --extra \\-target=foo`

The code specifically removes the double escape to create a clean command.

**Comment by surminus** [comment]
I wonder if `-target` could be a specific flag to pass to the wrapper?
